---
title: '&#39;Catch&#39; блока никогда не будет достигнут, поскольку &#39; &lt;name1&gt; &#39; наследует от &#39; &lt;name2&gt;&#39;'
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: d97bff73092fe1b92d2596961b0ce93c7a585bc3
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 05/04/2018
ms.locfileid: "33633205"
---
# <a name="39catch39-block-never-reached-because-39ltname1gt39-inherits-from-39ltname2gt39"></a>&#39;Catch&#39; блока никогда не будет достигнут, поскольку &#39; &lt;name1&gt; &#39; наследует от &#39; &lt;name2&gt;&#39;
Блок `Catch` в коде никогда не будет достигнут.  
  
 По умолчанию данное сообщение является предупреждением. Дополнительные сведения о скрытии предупреждений или обработке предупреждений как ошибок см. в разделе [Настройка предупреждений в Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **Идентификатор ошибки:** BC42029  
  
## <a name="to-correct-this-error"></a>Исправление ошибки  
  
-   Удалите лишний блок `Catch` .  
  
## <a name="see-also"></a>См. также  
 [Как: проверка кода с Try... Блок catch в Visual Basic](http://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Оператор Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
